# Generated by Django 2.2 on 2021-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_items_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
